name: 'Firmware CI'
on: [pull_request]

jobs:
  firmware-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Lint Python with ruff
        run: |
          pip install ruff
          cd firmware
          ruff check .
